version: "3.1"

# docker stack deploy --compose-file=docker-compose.pouchdb.yml pouchdb
networks:
  database:
    external:
      name: net

#volumes:
#  pouchdb:
#    driver: "local"

services:
  clickhouse:
    image: grengojbo/pouchdb-server
    volumes:
      - /var/srv/storage/pouchdb:/data
      - /var/srv/config/pouchdb/config.xml:/app/config.json
    ports:
      - "5984:5984"
    networks:
      - database
    environment:
      PORT: 5984
    deploy:
      placement:
        constraints:
          - node.role == worker
      mode: replicated
      replicas: 1
      #resources:
      #  limits:
      #    cpus: '0.60'
      #    memory: 1228M
      #  reservations:
      #    cpus: '0.50'
      #    memory: 1024M